wip

diff --git a/.github/workflows/bazel.yml b/.github/workflows/bazel.yml
--- a/.github/workflows/bazel.yml
+++ b/.github/workflows/bazel.yml
@@ -1,31 +1,48 @@
-name: CI
-
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+name: Minimal Bazel Build
+on: [push]
 
 jobs:
   build:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v3
+    name: Bazel
+    runs-on: blacksmith
     
-    - name: Mount bazel cache
-      uses: actions/cache@v3
-      with:
-        path: "~/.cache/bazel"
-        key: bazel-${{ runner.os }}-${{ github.sha }}
-        restore-keys: bazel-${{ runner.os }}-
+    steps:
+      - uses: actions/checkout@v4
+      
+      - name: Set up Bazel
+        uses: useblacksmith/setup-bazel@v1
+        with:
+          bazelisk-cache: true
 
-    - name: Install bazelisk
-      uses: bazelbuild/setup-bazelisk@v2
+      - name: Add bazel-remote directories
+        run: |
+          mkdir -p ${{ github.workspace }}/../bazel-remote/bin
+          BAZEL_REMOTE_DIR="$(realpath ${{ github.workspace }}/../bazel-remote)"
+          echo "BAZEL_REMOTE_DIR=$BAZEL_REMOTE_DIR" >> $GITHUB_ENV
+          echo "PATH=$PATH:$BAZEL_REMOTE_DIR/bin" >> $GITHUB_ENV
 
-    - name: Build
-      run: |
-        bazel build //...
+      - name: Download bazel-remote
+        run: |
+          wget -O $BAZEL_REMOTE_DIR/bin/bazel-remote \
+            https://github.com/buchgr/bazel-remote/releases/download/v2.4.4/bazel-remote-2.4.4-linux-x86_64 \
+          && chmod +x $BAZEL_REMOTE_DIR/bin/bazel-remote
 
-    - name: Test
-      run: |
-        bazel test //...
+      - name: Run bazel build
+        run: |
+          bazel-remote -port 8080 \
+            --dir $BAZEL_REMOTE_DIR/cache \
+            --max_size 6 \
+            --access_log_level=none &
+          bazel_remote_pid=$!
+          sleep .1
+          if ! kill -0 $bazel_remote_pid; then
+            echo "Bazel remote failed to start"
+            exit 1
+          fi
+          bazel \
+            --bazelrc=.aspect/bazelrc/ci.bazelrc \
+            build \
+            --remote_cache=http://localhost:8080 \
+            //...
+          kill $bazel_remote_pid
+          wait $bazel_remote_pid
